### ISSUE TITLE
Implementation of a Data structure to handle Driver Scenarios

### ISSUE THREAD

**Issue by kmustahsan** [kmustahsan/DD-Dispatcher#12]
@Tav0 How to implement this is completely at your discretion. This task should be completed, up to a certain point, before Deliverable 3 (3/29). If possible, please test your implementation. Also look into how we are interacting with it from Swift.

**Comment by Tav0** [comment]
This is almost done. Next time we meet I will discuss on how I went about this and how the data is structured. Some of the current structure will be modified a bit but no major changes of what has been done.
