### ISSUE TITLE
Create Group List/ Info

### ISSUE THREAD

**Issue by kmustahsan** [kmustahsan/DD-Dispatcher#3]
The task is when 'Groups' is clicked in the Hamburger menu, we need to show all the current Groups the user is in and once clicked upon, show details regarding that group. 
@ntarora

**Comment by ntarora** [comment]
2 screens done, with place holders for data.
Tableview to display the groups the user is part of need to get the list from backend/cache
Detailed view with group: image, name, desc, leave group button
